version: '3.8'
services:
  # python環境はdockerを使わずに作ってしばらく試してみる。
  # web:
  #   build:
  #     context: ./docker/web
  #     args:
  #       WWWUSER: "${WWWUSER:-1000}"
  #       WWWGROUP: "${WWWGROUP:-1000}"
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - ./:/work
  #   ports:
  #     - 8000:8000
  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gpttools
      MYSQL_USER: gpttools
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  db:
