version: '3.8'
services:
  web:
    build:
      context: ./docker/web
      args:
        WWWUSER: "${WWWUSER:-1000}"
        WWWGROUP: "${WWWGROUP:-1000}"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/work
    ports:
      - 8000:8000
  db:
    build:
      context: ./docker/mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gpt-tools
      MYSQL_USER: gpt-tools
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  db:
